

variables:
- ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
  - group: 'production-values'
- ${{ if eq(variables['Build.SourceBranchName'], 'preprod') }}:
  - group: 'preprod-values'
- ${{ if eq(variables['Build.SourceBranchName'], 'test') }}:
  - group: 'test-values'
- ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
  - group: 'develop-values'
