parameters:
  - name: imageName
    type: string

  - name: tag
    type: string

  - name: dependsOn
    type: string
    default: ''

jobs:
  - job: docker_build
    displayName: Build and Release
    ${{ if ne(parameters.dependsOn, '') }}:
      dependsOn: ${{ parameters.dependsOn }}
    steps:
      - script: git submodule update --init --recursive
        displayName: Git get submodules

      - script: echo "##vso[task.setvariable variable=tag]${{ parameters.tag }}$(git describe --tags --long | sed '0,/-/s/-/./')"
        displayName: Append tag with git describe

      - task: Docker@2
        displayName: Build docker image
        inputs:
          command: build
          repository: ${{ parameters.imageName }}
          Dockerfile: Dockerfile
          tags: ${{ parameters.tag }}

      - script: docker run -ti --entrypoing "pipenv run pytest" ${{ parameters.imageName }}
        displayName: 'Running tests'

