jobs:
  - job: run_pytest
    displayName: Test
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      TEST: 1
    steps:
      - script: sudo apt update
        displayName: 'Update repo'

      - script: sudo apt install -y pkg-config gcc libsecp256k1-dev libzmq3-dev
        displayName: 'Install packages'

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'

      - script: pip install --upgrade twine wheel setuptools pip pipenv importlib-metadata
        displayName: 'Upgrading/installing Python packages'

      - script: python -m pipenv install -d
        displayName: 'Installing dependencies from Pipenv'

      - script: python -m pipenv run pytest
        displayName: 'Run tests'
