parameters:
  - name: imageName
    type: string

  - name: tag
    type: string

  - name: dependsOn
    type: string
    default: ''

jobs:
  - job: build_test_push
    displayName: Build, Test, Push
    ${{ if ne(parameters.dependsOn, '') }}:
      dependsOn: ${{ parameters.dependsOn }}
    steps:
      - script: git submodule update --init --recursive
        displayName: Git get submodules

      - script: echo "##vso[task.setvariable variable=tag]${{ parameters.tag }}$(git describe --tags --long | sed '0,/-/s/-/./')"
        displayName: Append tag with git describe

      - task: Docker@2
        displayName: Build docker image
        inputs:
          command: build
          repository: ${{ parameters.imageName }}
          Dockerfile: Dockerfile
          tags: ${{ parameters.tag }}

      - script: docker run -e TEST=1 -v /var/run/docker.sock:/var/run/docker.sock ${{ parameters.imageName }}:${{ parameters.tag }} pipenv run pytest
        displayName: 'Run tests'
