parameters:
  - name: imageName
    type: string

  - name: tag
    type: string

  - name: dependsOn
    type: string

jobs:
  - job: docker_build
    displayName: Build and Release
    dependsOn: ${{ parameters.dependsOn }}
    steps:
      - script: echo "##vso[task.setvariable variable=tag]${{ parameters.tag }}$(git describe --tags --long | sed '0,/-/s/-/./')"
        displayName: Append tag with git describe
      
      - task: Docker@2
        displayName: Build docker image
        inputs:
          command: build
          repository: ${{ parameters.imageName }}
          Dockerfile: Dockerfile
          tags: ${{ parameters.tag }}
      
      - task: Docker@2
        displayName: Build docker latest image
        condition: eq(variables['Build.SourceBranchName'], 'master')
        inputs:
          command: build
          repository: ${{ parameters.imageName }}
          Dockerfile: Dockerfile
          tags: latest

      - task: Docker@2
        displayName: Push image
        inputs:
          command: push
          repository: ${{ parameters.imageName }}
          containerRegistry: dockerHub
          tags: ${{ parameters.tag }}

      - task: Docker@2
        displayName: Push latest image
        condition: eq(variables['Build.SourceBranchName'], 'master')
        inputs:
          command: push
          repository: ${{ parameters.imageName }}
          containerRegistry: dockerHub
          tags: latest